import Head from "next/head";
import { Header } from "@/components/Header";
import { Comments } from "@/components/Commtents";

const Comment = () => {
  return (
    <div>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Comments />
    </div>
  );
};
export default Comment;
