import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Header } from "@/components/Header";
import { useRouter } from "next/router";

const PostId = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* ファイル名と一致しないとダメ [id] = query.id　*/}
      <div>{router.query.id}</div>
    </div>
  );
};
export default PostId;
