import Head from "next/head";
import { Header } from "@/components/Header";
import { Comment } from "@/components/Comment";
import { useComment } from "@/hooks/useComment";

const CommentId = () => {
  const { data, error, isLoading } = useComment();

  return (
    <div>
      <Head>
        <title>{data?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Comment />
    </div>
  );
};
export default CommentId;
