import Head from "next/head";
import { Header } from "@/components/Header";
import { User } from "@/components/User";
import { useUser } from "@/hooks/useUser";
import { useRouter } from "next/router";

const UserId = () => {
  const { data, error, isLoading } = useUser();
  const router = useRouter();
  console.log(router.query);
  return (
    <div>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <User />
    </div>
  );
};
export default UserId;
