import Head from "next/head";
import { Header } from "@/components/Header";
import { usePost } from "@/hooks/usePost";
import { User } from "@/components/User";

const UserId = () => {
  const { data, error, isLoading } = usePost();
  return (
    <div>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <User />
    </div>
  );
};
export default UserId;
