import Head from "next/head";
import { Header } from "@/components/Header";
import { usePost } from "@/hooks/usePost";
import { Post } from "@/components/Post";

const PostsId = () => {
  const { post, user, error, isLoading } = usePost();
  return (
    <div>
      <Head>
        <title>{post?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Post />
    </div>
  );
};
export default PostsId;
